### ISSUE TITLE
Unexpected behaviour in extra emphasis markers' interaction with other markers and each other

### ISSUE THREAD

**Issue by quzyte** [kjambunathan/org-extra-emphasis#10]
The following org code shows a few scenarios where the extra emphasis markers do not behave as expected.

    * Org Extra Emphasis Markers
    ** =!!= and =!@= override bold, italic, etc.
    /a   man a plan a canal   panama/
    /a !!man a plan a canal!! panama/

    /a   man a plan a canal   panama/
    /a !@man a plan a canal!@ panama/

    ** Bold, italic, etc. don't override =!!= or =!@= though
      a *man /a _plan_ a/ canal* panama  
    !!a *man /a _plan_ a/ canal* panama!!

      a *man /a _plan_ a/ canal* panama  
    !@a *man /a _plan_ a/ canal* panama!@
      
    ** =!!= and =!@= are mutually incompatible (unlike the screenshot shown in readme)
    !!a !@man a plan a canal!@ panama!!
    !@a !!man a plan a canal!! panama!@

    ** Highlight is not shown in =hl-line-mode=
    !!a man a plan!! !@a canal panama!@
    !!a man a plan!! !@a canal panama!@

This is rendered as:
![Screenshot from 2023-02-09 20-14-07](https://user-images.githubusercontent.com/43617268/217849057-569e0449-062d-4dd3-8b25-736b6d1a1b8e.png)
The example illustrates the issues, namely:
- The extra emphasis faces override the default bold, italic, underline, and other faces instead of complimenting them.
- The other way around works fine.
- The yellow highlight and red display faces also override each other (unlike the screenshot shown in the readme).
- The yellow highlight (but curiously not the red display) is not shown in hl-line-mode

**Comment by kjambunathan** [comment]
This is what I see after the above fix ...

![Screenshot from 2023-02-10 07-47-40](https://user-images.githubusercontent.com/19869864/217983653-391b7dbc-b09a-4a37-937e-c926190d1b31.png)

**Comment by kjambunathan** [comment]
> The yellow highlight (but curiously not the red display) is not shown in hl-line-mode

`Red` is background, and `Yellow` is foreground.

The foreground of `hl-line` face wins over the foreground of the underlying  face.  This is the default Emacs behaviour.  You can't change it.

**Comment by quzyte** [comment]
Thank you for the quick fix! Works as expected now.
