### ISSUE TITLE
Why are there (sleep-for ...) calls in the .el code?

### ISSUE THREAD

**Issue by rnikander** [kjambunathan/org-extra-emphasis#7]
Were these left in by mistake? There are two calls that seem to be slowing down my emacs startup. Search for "sleep-for" in the org-extra-emphasis.el file.

**Comment by kjambunathan** [comment]
There is a messge right before the sleep.  This way the warning message
will remain in the echo area, and one can notice the warning.

If odt is of no interest to you, you can comment it out.

I need to check if it hapens on every export or only once.
Show quoted text

**Comment by rnikander** [comment]
For me it's happening when I simply load the .el file. I never export anything.

**Comment by kjambunathan** [comment]
I have removed the `sleep-for` calls.

**Comment by kjambunathan** [comment]
There is a messge right before the sleep for message.  This way the warnin
message will remain in the echo area, and one can notice the warning.

If odt is of no interest to you, you can comment it out.

I need to check if it hapens on every export or only once.
